
stages:
  - docker
  - test
  - build
  - deploy

build-data-discovery:
  stage: docker
  image: docker:latest
  services: 
    - docker:dind
  tags:
    - dind
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD  | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE"/data-discovery:latest ./services/data-discovery/
    - docker push "$CI_REGISTRY_IMAGE"/data-discovery:latest
  only:
    changes:
      - services/data-discovery/Dockerfile
      - services/data-discovery/requirements.txt


test-data-discovery:
  stage: test
  image: alpine/curl:latest
  before_script:
    - echo -n $CI_REGISTRY_PASSWORD  | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  services:
    - name: "$CI_REGISTRY_IMAGE"/data-discovery:latest
      command: ["--port 8080"]
  script:
    - curl data-discovery/
    
