[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = [
  ".", "datastore"
]
env = [
    "PYTHONBREAKPOINT  = 0",
    "PYTEST_DEBUG = 1"
]